[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "shuttleai"
dynamic = ["version"]
description = "Access Shuttle AI's API via an easy-to-use Python wrapper. Dashboard: https://shuttleai.com Discord: https://discord.gg/shuttleai"
authors = [
    { name = "Tristan Liu", email = "tristan@shuttleai.app" },
    { name = 'Christian "Thoth" Heru', email = "chris@shuttleai.app" },
]
requires-python = ">=3.9,<4"
readme = "README.md"
maintainers = [{ name = 'Christian "Thoth" Heru', email = "chris@shuttleai.app" }]
keywords = [
    "shuttleai",
    "ai",
    "gpt",
    "claude",
    "api",
    "free",
    "chatgpt",
    "gpt-4",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.32.4,<3",
    "aiohttp>=3.9.5,<4",
    "orjson>=3.10.3,<4",
    "pydantic>=2.7.3,<3",
    "httpx>= 0.28.1, < 1",
    "python-dateutil>=2.9.0.post0,<3",
    "pyreadline3>=3.4.1,<4",
    "aiofiles>=25.0.0,<26",
    "types-aiofiles>=25.1.0.20251011,<26",
    "hatchling>=1.27.0",
]

[project.urls]
Homepage = "https://github.com/shuttleai"
Repository = "https://github.com/shuttleai/shuttleai-python"
Documentation = "https://docs.shuttleai.com"
Dashboard = "https://shuttleai.com"
Discord = "https://discord.gg/shuttleai"
PyPI = "https://pypi.org/project/shuttleai"

[project.scripts]
shuttleai = "shuttleai.cli.__main__:main"
clean = "etc.tools.clean:clean_all"
key = "etc.tools.key:show_key"
contr = "etc.tools.contributors:main"

[dependency-groups]
dev = [
    "ruff>=0.14.5,<0.15",
    "mypy>=1.10.0,<2",
    "black>=25.11.0,<26",
    "types-requests>=2.32.4.20250913,<3",
    "pyyaml>=6.0.1,<7",
    "types-pyyaml>=6.0.12.20240311,<7",
    "hatch>=1.15.1",
]

[tool.hatch.version]
path = "shuttleai/__init__.py"

[tool.ruff]
select = ["E", "F", "W", "Q", "I"]
ignore = ["E203"]
fixable = ["ALL"]
unfixable = []
line-length = 120
extend-select = ["B"]

[tool.black]
line-length = 120
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
exclude = ["docs", "tests", "examples", "tools", "build", "etc"]
